from colorama import Fore

#
# scene2arr.py
#
SCENE2ARR_DB_FILE = "scene2arr.db"
PRE_DB_FILE = "pre.db"
IRC_CONFIG_FILE = "irc.yaml"

#
# scenerename.py
#
SCENERENAME_DB_FILE = "scenerename.db"

#
# scene2arr.py, scenerename.py
#
VERBOSE = f"{Fore.YELLOW}VERBOSE:{Fore.RESET}"
ERROR = f"{Fore.RED}ERROR:{Fore.RESET}"
RENAMED = f"{Fore.BLUE}RENAMED:{Fore.RESET}"
WRONGFILESIZE = f"{Fore.RED}WRONG FILESIZE:{Fore.RESET}"
NOTWHITELISTED = f"SKIPPING {Fore.RED}NOT WHITELISTED{Fore.RESET}:"
BLACKLISTED = f"SKIPPING {Fore.RED}BLACKLISTED{Fore.RESET}:"
SKIPPINGOK = f"SKIPPING {Fore.GREEN}OK{Fore.RESET}:"
SKIPPINGCORRUPT = f"SKIPPING {Fore.RED}CORRUPT{Fore.RESET}:"
SKIPPINGNOTFOUND = f"SKIPPING {Fore.MAGENTA}NOT FOUND{Fore.RESET}:"
SKIPPINGUNPROCESSED = f"SKIPPING {Fore.CYAN}UNPROCESSED{Fore.RESET}:"
MATCHED = f"{Fore.GREEN}MATCHED:{Fore.RESET}"
NOTFOUND = f"{Fore.MAGENTA}NOT FOUND:{Fore.RESET}"
OK = f"{Fore.GREEN}OK:{Fore.RESET}"
CORRUPT = f"{Fore.RED}CORRUPT:{Fore.RESET}"
SKIPPING = f"{Fore.WHITE}SKIPPING:{Fore.RESET}"
IGNORED = f"{Fore.MAGENTA}IGNORED:{Fore.RESET}"
ADDED = f"{Fore.GREEN}ADDED:{Fore.RESET}"
REMOVED = f"{Fore.GREEN}REMOVED:{Fore.RESET}"
INFO = "INFO:"
